- hosts: localhost
  connection: local
  collections:
    - ansible.posix
    
  roles:
    - webofmars.dummy
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi

  pre_tasks:
    - selinux: state=disabled
